[[language]]
name = "text"
scope = "text"
file-types = ["txt", "log"]
indent = { tab-width = 4, unit = "    " }
text-width = 0  
rulers = [1000]

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = "    " }
text-width = 120  
rulers =[121]

[[language]]
name = "python"
text-width = 100  
rulers=[101]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "    " }

[[language]]
text-width = 100  
rulers =[101]
name = "typescript"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "php"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "java"
text-width = 100  
rulers =[101]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
text-width = 100  
rulers =[101]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
text-width = 100  
rulers =[101]
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
text-width = 100  
rulers =[101]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
text-width = 100  
rulers =[101]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"
